# NumPy Array Object: 205 exercises

**LINK -> https://w3resource.com/python-exercises/numpy/index-array.php**

---

In [1]:
import numpy as np

### 1\. Write a NumPy program to print the NumPy version in your system.

In [2]:
np.__version__

'1.23.1'

### 2\. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

In [5]:
list1 = [1, 2, 3, 4, 5]
print("Python list:", list1)
print(type(list1))

arr1 = np.array(list1)
print("\nNumPy array:", arr1)
print(type(arr1))

Python list: [1, 2, 3, 4, 5]
<class 'list'>

NumPy array: [1 2 3 4 5]
<class 'numpy.ndarray'>


### 3\.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [6]:
np.arange(2, 11).reshape(3, 3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### 4\. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

In [9]:
arr = np.zeros((10))
print("Null vector:", arr)

arr[5] = 11
print("After updating the vector:", arr)

Null vector: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After updating the vector: [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


### 5\. Write a NumPy program to create an array with values ranging from 12 to 38.

In [12]:
np.arange(12, 38)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

### 6\. Write a NumPy program to reverse an array (first element becomes last).

In [57]:
arr = np.arange(12, 38)
print("Original array:\n", arr)
print("Reverse array:\n", sorted(arr, reverse=True))

Original array:
 [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
 [37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12]


In [59]:
# Solution
arr[::-1]

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

### 7\. Write a NumPy program to convert an array to a float type.

In [96]:
arr = np.array([10, 15, 25, 40, 60])
print('Array:', arr)
print('Data type:', arr.dtype)

arr = arr.astype(np.float64)
# arr = np.asarray(arr, dtype=np.float64)
print('\nFloat array:', arr)
print('Data type:', arr.dtype)

Array: [10 15 25 40 60]
Data type: int64

Float array: [10. 15. 25. 40. 60.]
Data type: float64


In [97]:
# Solution
a = [1, 2, 3, 4]
print("Original array")
print(a)
x = np.asfarray(a)
print("Array converted to a float type:")
print(x)

Original array
[1, 2, 3, 4]
Array converted to a float type:
[1. 2. 3. 4.]


### 8\. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [111]:
arr = np.ones((6, 6))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

### 9\. Write a NumPy program to add a border (filled with 0's) around an existing array.

In [289]:
arr = np.ones((3, 3))
print("Original array:\n", arr)

arr = np.insert(arr, 0, 0, axis=0)
arr = np.insert(arr, 0, 0, axis=1)
arr = np.insert(arr, arr.shape[0], 0, axis=0)
arr = np.insert(arr, arr.shape[1], 0, axis=1)
arr

Original array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [290]:
# Solution
x = np.ones((3, 3))
print("Original array:\n", x)

x = np.pad(x, pad_width=1, constant_values=0)
print("0 on the border and 1 inside in the array:\n", x)

Original array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array:
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 10\. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [370]:
arr = np.ones((8, 8))
arr[::2, ::2] = 0
arr[1::2, 1::2] = 0
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

### 11\. Write a NumPy program to convert a list and tuple into arrays.

In [5]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array:", np.asarray(my_list))

my_tuple = ([8, 4, 6], [1, 2, 3])
print("Tuple to array:\n", np.asarray(my_tuple))

List to array: [1 2 3 4 5 6 7 8]
Tuple to array:
 [[8 4 6]
 [1 2 3]]


### 12\. Write a NumPy program to append values to the end of an array.

In [392]:
arr = np.array([10, 20, 30])
print("Array:\n", arr)

arr = np.append(arr, [[40, 50, 60], [70, 80, 90]])
print("After appending values to the end of the array:\n", arr)

Array:
 [10 20 30]
After appending values to the end of the array:
 [10 20 30 40 50 60 70 80 90]


### 13\. Write a NumPy program to create an empty and a full array.

In [406]:
print("Empty array:\n", np.empty((3, 3)))
print("\nFull array:\n", np.full((3, 3), 5))

Empty array:
 [[2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]]

Full array:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]


### 14\. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees and vice versa. Values are stored into a NumPy array.

|![Fahrenheit-to-Celsius-Formula](https://d138zd1ktt9iqe.cloudfront.net/media/seo_landing_files/fahrenheit-to-celsius-02-1639022494.png)||![Celsius-to-Fahrenheit-Formula](https://d138zd1ktt9iqe.cloudfront.net/media/seo_landing_files/c-to-f-formula-1638963368.png)|
|-|-|-|

In [475]:
fvalues = np.array([0, 12, 45.21, 34, 99.91])
cvalues = np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0])

def to_fahnt(arr):
    f_list = []
    for x in np.nditer(arr):
        x = x * 9 / 5 + 32
        f_list.append(round(x, 2))
    return np.array(f_list).reshape(arr.shape)

def to_cels(arr):
    c_list = []
    for x in np.nditer(arr):
        x = (x - 32) * 5 / 9
        c_list.append(round(x, 2))
    return np.array(c_list).reshape(arr.shape)

print("Values in Fahrenheit:", fvalues)
print("Converted values in Celsius:", to_cels(fvalues))
print()
print("Values in Celsius:", cvalues)
print("Converted values in Fahrenheit:", to_fahnt(cvalues))

Values in Fahrenheit: [ 0.   12.   45.21 34.   99.91]
Converted values in Celsius: [-17.78 -11.11   7.34   1.11  37.73]

Values in Celsius: [-17.78 -11.11   7.34   1.11  37.73   0.  ]
Converted values in Fahrenheit: [-0.   12.   45.21 34.   99.91 32.  ]


In [474]:
# Solution
F = np.array([0, 12, 45.21, 34, 99.91, 32])
print("Values in Fahrenheit degrees:\n", F)
print("Values in  Centigrade degrees:")
print(np.round((F * 5/9 - 32*5/9), 2))

C = np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0])
print("\nValues in Centigrade degrees:\n", C)
print("Values in  Fahrenheit degrees:")
print(np.round((C * 9/5 + 32), 2))

Values in Fahrenheit degrees:
 [ 0.   12.   45.21 34.   99.91 32.  ]
Values in  Centigrade degrees:
[-17.78 -11.11   7.34   1.11  37.73   0.  ]

Values in Centigrade degrees:
 [-17.78 -11.11   7.34   1.11  37.73   0.  ]
Values in  Fahrenheit degrees:
[-0.   12.   45.21 34.   99.91 32.  ]


### 15\. Write a NumPy program to find the real and imaginary parts of an array of complex numbers.

In [10]:
arr = np.array([1.00000000+0.j, 0.70710678+0.70710678j, 12-8j])
print(arr)
print("Real part of the array:\n", arr.real)
print("Imaginary part of the array:\n", arr.imag)

[ 1.        +0.j          0.70710678+0.70710678j 12.        -8.j        ]
Real part of the array:
 [ 1.          0.70710678 12.        ]
Imaginary part of the array:
 [ 0.          0.70710678 -8.        ]


### 16\. Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [11]:
arr = np.random.rand(3, 3)
print("Size of the array:", arr.size)
print("Length of one array element in bytes:", arr.itemsize)
print("Total bytes consumed by the elements of the array:", arr.nbytes)

Size of the array: 9
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 72


### 17\. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

In [32]:
arr1 = np.array([1, 2, 4, 6, 8, 9])
arr2 = np.array([2, 3, 4, 5, 7, 10])
np.in1d(arr1, arr2)

array([False,  True,  True, False, False, False])

### 18\. Write a NumPy program to find common values between two arrays.

In [34]:
arr1 = np.array([1, 2, 4, 6, 8, 9])
arr2 = np.array([2, 3, 4, 5, 7, 10])
np.intersect1d(arr1, arr2)

array([2, 4])

### 19\. Write a NumPy program to get the unique elements of an array.

In [47]:
arr = np.array([1, 3, 3, 5, 5, 8, 12, 20, 13, 8, 21, 20])
np.unique(arr)

array([ 1,  3,  5,  8, 12, 13, 20, 21])

### 20\. Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.

In [2]:
arr1 = np.array([1, 2, 4, 6, 8, 9])
arr2 = np.array([2, 3, 4, 5, 7, 10])
np.setdiff1d(arr1, arr2)

array([1, 6, 8, 9])

### 21\. Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.

In [12]:
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70])
np.setxor1d(arr1, arr2)

array([ 0, 20, 30, 50, 60, 70, 80])

### 22\. Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays.

In [5]:
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70])
np.union1d(arr1, arr2)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

### 23\. Write a NumPy program to test whether all elements in an array evaluate to True.

In [23]:
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))

False
True
False
True


### 24\. Write a NumPy program to test whether any array element along a given axis evaluates to True.

In [22]:
print(np.any([[True,False],[True,True]]))
print(np.any([[True,True],[True,True]]))
print(np.any([10, 20, 0, -50]))
print(np.any([10, 20, -50]))

True
True
True
True


### 25\. Write a NumPy program to construct an array by repeating.

In [57]:
arr = np.array([1, 2, 3, 4])
print("Orignal array:", arr)

print("Repeating 2 times:", np.array([arr] * 2).flatten())
print("Repeating 3 times:", np.array([arr] * 3).flatten())

Orignal array: [1 2 3 4]
Repeating 2 times: [1 2 3 4 1 2 3 4]
Repeating 3 times: [1 2 3 4 1 2 3 4 1 2 3 4]


In [59]:
# Solution
print("Repeating 2 times:", np.tile(arr, 2))
print("Repeating 3 times:", np.tile(arr, 3))

Repeating 2 times: [1 2 3 4 1 2 3 4]
Repeating 3 times: [1 2 3 4 1 2 3 4 1 2 3 4]


### 26\. Write a NumPy program to repeat elements of an array.

In [64]:
print("Original array:", arr)
np.repeat(arr, 2)

Original array: [1 2 3 4]


array([1, 1, 2, 2, 3, 3, 4, 4])

### 27\. Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.

In [68]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("Index of the Maximum Value:", arr.argmax())
print("Index of the Minimum Value:", arr.argmin())

Index of the Maximum Value: 5
Index of the Minimum Value: 0


### 28\. Write a NumPy program compare two given arrays.

In [75]:
a = np.array([1, 3])
b = np.array([5, 7])
print('Array a:', a)
print('Array b:', b)

print("\na > b:", np.greater(a, b))  # a > b
print("a >= b:", np.greater_equal(a, b))  # a >= b
print("a < b:", np.less(a, b))  # a < b
print("a <= b:", np.less_equal(a, b))  # a <= b

Array a: [1 3]
Array b: [5 7]

a > b: [False False]
a >= b: [False False]
a < b: [ True  True]
a <= b: [ True  True]


### 29\. Write a NumPy program to sort an along the first, last axis of an array.

In [87]:
arr = np.array([[2, 7], [12, 3], [5, 10]])
print("Original array:\n", arr)

print("Sorted by columns:\n", np.sort(arr, axis=0))
print("Sorted by rows:\n", np.sort(arr, axis=1))

Original array:
 [[ 2  7]
 [12  3]
 [ 5 10]]
Sorted by columns:
 [[ 2  3]
 [ 5  7]
 [12 10]]
Sorted by rows:
 [[ 2  7]
 [ 3 12]
 [ 5 10]]


### 30\. Write a NumPy program to sort pairs of first name and last name return their indices. (first by last name, then by first name).

In [60]:
first_names = ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
np.lexsort((first_names, last_names))

array([1, 3, 2, 4, 0])

In [62]:
# Sort two columns of numbers:
a = [1,5,1,4,3,4,4] # First column
b = [9,4,0,4,0,2,1] # Second column
ind = np.lexsort((b,a)) # Sort by a, then by b
ind

array([2, 0, 4, 6, 5, 3, 1])

### 31\. Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

In [77]:
arr = np.array([[0, 10, 20], [20, 30, 40]])
print("Valeus bigger than 10:", arr[arr > 10])
print("Their indices are", np.nonzero(arr > 10))

Valeus bigger than 10: [20 20 30 40]
Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))


### 32\. Write a NumPy program to save a NumPy array to a text file.

In [7]:
arr = np.random.rand(3, 3)
np.save('array.npy', arr)

In [10]:
np.load('array.npy')

array([[0.55770331, 0.16262395, 0.54884736],
       [0.88677755, 0.13648052, 0.80865767],
       [0.94826595, 0.69586626, 0.25409771]])

### 33\. Write a NumPy program to find the memory size of a NumPy array.

In [16]:
arr.nbytes

72

### 34\. Write a NumPy program to create an array of ones and an array of zeros.

In [27]:
a1 = np.ones((3, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
a1.astype('int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [26]:
a2 = np.zeros((3, 3))
a2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
a2.astype('int32')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

### 35\. Write a NumPy program to change the dimension of an array.

In [5]:
arr = np.arange(6)
print(arr)
arr.shape

[0 1 2 3 4 5]


(6,)

In [8]:
arr = arr.reshape(2, 3)
print(arr)
arr.shape

[[0 1 2]
 [3 4 5]]


(2, 3)

In [13]:
# Solution
x = np.array([1, 2, 3, 4, 5, 6])
print("x =", x)
print("shape:", x.shape)
print()
# change array shape
x.shape = (2, 3)
print(x)
print("shape:", x.shape)

x = [1 2 3 4 5 6]
shape: (6,)

[[1 2 3]
 [4 5 6]]
shape: (2, 3)


### 36\. Write a NumPy program to create a contiguous flattened array.

In [29]:
x = np.array([[10, 20, 30], [40, 50, 60]])
print("Original array:\n", x)
print("\nFlattened array:", x.flatten())

Original array:
 [[10 20 30]
 [40 50 60]]

Flattened array: [10 20 30 40 50 60]


In [31]:
# Solution
x = np.array([[10, 20, 30], [20, 40, 50]])
print("Original array:\n", x)

y = np.ravel(x)
print("\nNew flattened array:", y)

Original array:
 [[10 20 30]
 [20 40 50]]

New flattened array: [10 20 30 20 40 50]


### 37\. Write a NumPy program to create a 2-dimensional array of size 2 x 3 (composed of 4-byte integer elements), also print the shape, type and data type of the array.

In [41]:
arr = np.arange(1, 7, dtype=np.int32)
print(type(arr))
print("array shape:", arr.shape)
arr

<class 'numpy.ndarray'>
array shape: (6,)


array([1, 2, 3, 4, 5, 6], dtype=int32)

###  38\. Write a NumPy program to create a new shape to an array without changing its data.

In [51]:
x = np.arange(1, 7).reshape(3, 2)
print(x)
print("Reshape 2x3:\n", np.reshape(x, (2, 3)))

[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
 [[1 2 3]
 [4 5 6]]


### 39\. Write a NumPy program to change the data type of an array.

In [90]:
x = np.random.rand(3, 4)
print(x)
print("Data type:", x.dtype)
print("Change data type to float16:\n", np.array(x, dtype=np.float16))
# print("Change data type to float16:\n", x.astype(np.float16))

[[0.68941344 0.52735828 0.43434829 0.61387401]
 [0.58890368 0.41005548 0.1864511  0.42074089]
 [0.67876431 0.0363673  0.29878403 0.04055936]]
Data type: float64
Change data type to float16:
 [[0.6895  0.5273  0.4343  0.614  ]
 [0.589   0.4102  0.1864  0.4207 ]
 [0.6787  0.03638 0.2988  0.04056]]


### 40\. Write a NumPy program to create a new array of 3*5, filled with 2.

In [105]:
np.full((3, 5), 2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

### 41\. Write a NumPy program to create an array of 10's with the same shape and type of a given array.

In [119]:
x = np.arange(4, dtype=np.int64)
print("Array:", x)
np.full_like(x, 10)

Array: [0 1 2 3]


array([10, 10, 10, 10])

### 42\. Write a NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere.

In [131]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 43\. Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.

In [138]:
np.diag([4, 5, 6, 8])

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

### 44\. Write a NumPy program to create a 1-D array going from 0 to 50 and an array from 10 to 50.

In [140]:
arr1 = np.arange(50)
arr2 = np.arange(10, 50)
print("Array from 0 to 50:\n", arr1)
print("Array from 10 to 50:\n", arr2)

Array from 0 to 50:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
Array from 10 to 50:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 45\. Write a NumPy program to Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive.

In [144]:
np.linspace(2.5, 6.5, 30)

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

### 46\. Write a NumPy program to create a 1-D array of 20 element spaced evenly on a log scale between 2. and 5., exclusive.

In [146]:
np.logspace(2, 5, 20)

array([   100.        ,    143.84498883,    206.91380811,    297.63514416,
          428.13323987,    615.84821107,    885.86679041,   1274.2749857 ,
         1832.98071083,   2636.65089873,   3792.69019073,   5455.59478117,
         7847.59970351,  11288.37891685,  16237.76739189,  23357.2146909 ,
        33598.18286284,  48329.30238572,  69519.27961776, 100000.        ])

### 47\. Write a NumPy program to create an array which looks like below array.

In [161]:
np.tri(4, 3, -1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])